# riot --formatted=TURTLE /home/gehau/git/codelijst-chemische_stof/src/main/resources/be/vlaanderen/omgeving/data/id/conceptscheme/chemische_stof/skos_chemont_2_1.ttl /home/gehau/git/codelijst-chemische_stof/src/main/resources/be/vlaanderen/omgeving/data/id/conceptscheme/chemische_stof/chemische_stof.ttl > /tmp/cs.ttl
##sparql --results=TURTLE --data=/tmp/cs.ttl  --query beperk_chemont.rq
prefix skos:  <http://www.w3.org/2004/02/skos/core#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix dbo:   <http://dbpedia.org/ontology/>
prefix cs:    <https://data.vlaanderen.be/ns/chemische_stof#>
prefix dbp:   <http://dbpedia.org/property/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix csc: <https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/>
prefix vlcs:  <https://data.omgeving.vlaanderen.be/id/conceptscheme/>
prefix xkos:        <http://rdf-vocabulary.ddialliance.org/xkos#>
prefix rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


construct
{
?s ?p ?o ; skos:broaderTransitive ?broader .
?broader ?p2 ?o2 .
vlcs:chemische_stof ?p3 ?o3 .
?cl ?pcl ?ocl .
?l ?pl ?ol .
#?broader skos:narrowerTransitive ?s .
}

where
{
{
?s a dbo:ChemicalCompound ;
skos:broader+ ?broader ;
?p ?o .
?broader ?p2 ?o2 .
}
UNION
{
vlcs:chemische_stof ?p3 ?o3 .
}
UNION
{
   ?cl ?pcl ?ocl ; a xkos:ClassificationLevel .
}
UNION
{
   ?l ?pl ?ol ; a rdf:List .
}
}




