##sparql --results=TURTLE --data=/home/gehau/Desktop/ChemOnt_2_1.ttl  --query chemont_to_skos.rq | sed -e 's;http://purl.obolibrary.org/obo/;https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/;'> /home/gehau/git/codelijst-chemische_stof/src/main/resources/be/vlaanderen/omgeving/data/id/conceptscheme/chemische_stof/skos_chemont_2_1.ttl
prefix skos:  <http://www.w3.org/2004/02/skos/core#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix dbo:   <http://dbpedia.org/ontology/>
prefix cs:    <https://data.vlaanderen.be/ns/chemische_stof#>
prefix dbp:   <http://dbpedia.org/property/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix csc: <http://purl.obolibrary.org/obo/>
prefix vlcs:  <https://data.omgeving.vlaanderen.be/id/conceptscheme/>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

construct

{
vlcs:chemische_stof a skos:ConceptScheme ;
skos:prefLabel ?label ;
skos:definition ?definition ;
skos:altLabel ?altLabel ;
skos:notation ?notation .

}

where

{
<http://purl.obolibrary.org/obo/CHEMONTID_9999999> a owl:Class ;
    rdfs:label ?la .
    optional {<http://purl.obolibrary.org/obo/CHEMONTID_9999999> <http://purl.obolibrary.org/obo/IAO_0000115> ?def . BIND(STRLANG(?def, "en") AS ?definition) }
    optional {<http://purl.obolibrary.org/obo/CHEMONTID_9999999> <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> ?al . BIND(STRLANG(?al, "en") AS ?altLabel)}
    optional { <http://purl.obolibrary.org/obo/CHEMONTID_9999999> <http://www.geneontology.org/formats/oboInOwl#id> ?notation }
    optional {<http://purl.obolibrary.org/obo/CHEMONTID_9999999> <http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym> ?al . BIND(STRLANG(?al, "en") AS ?altLabel)}
    BIND(STRLANG(?la, "en") AS ?label)
}