PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
prefix chebi:  <http://purl.obolibrary.org/obo/chebi/>
prefix geneontology: <http://www.geneontology.org/formats/oboInOwl#>
prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
prefix obo:   <http://purl.obolibrary.org/obo/>
prefix dbo:   <http://dbpedia.org/ontology/>
prefix conceptscheme: <https://data.omgeving.vlaanderen.be/id/conceptscheme/>
prefix dbp:   <http://dbpedia.org/property/>
prefix owl:   <http://www.w3.org/2002/07/owl#>
construct
{
    ?group ?p ?o .
}
where
{
    ?stof dbp:inchikey ?key ; skos:broader+ ?group  .
    ?group ?p ?o .
}
